/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Locale;
import org.apache.commons.lang3.StringUtils;


public class App {

    public String getGreeting() {
        return StringUtils.upperCase("Hello World!", Locale.ENGLISH);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
