[tools]
# renovate: datasource=java-version depName=java
java = "semeru-openj9-21.0.10+7"   # derive: mise ls-remote java | grep semeru-openj9-21 | tail -1

# renovate: datasource=node-version depName=node
node = "24"

# renovate: datasource=github-releases depName=hadolint/hadolint
hadolint = "2.14.0"

# renovate: datasource=github-releases depName=nektos/act
act = "0.2.87"

# renovate: datasource=github-releases depName=gitleaks/gitleaks
gitleaks = "8.29.0"

# renovate: datasource=github-releases depName=aquasecurity/trivy
trivy = "0.69.3"
